# ========================
# STAGE 1: builder
# ========================
FROM python:3.11-slim AS builder

WORKDIR /app

COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# ========================
# STAGE 2: test
# ========================
FROM builder AS test

COPY app /app

ENV PYTHONPATH=/app

RUN pytest app/tests

# ========================
# STAGE 3: final
# ========================
FROM python:3.11-slim AS final

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=builder /usr/local/bin /usr/local/bin

COPY app /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["python", "src/app.py"]
